# Generated by Django 5.1.2 on 2025-10-23 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('max_assets_per_category', models.IntegerField(default=3)),
                ('max_dependents', models.IntegerField(default=1)),
                ('max_beneficiaries', models.IntegerField(default=3)),
                ('has_reward_tracker', models.BooleanField(default=False)),
                ('reward_percentage', models.IntegerField(default=0, help_text='Reward percentage every 3 years')),
                ('can_export_reports', models.BooleanField(default=True)),
                ('can_download_documents', models.BooleanField(default=True)),
                ('can_manage_businesses', models.BooleanField(default=True)),
                ('can_manage_professional_contacts', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('role_type', models.CharField(choices=[('admin', 'Admin'), ('verifier', 'Verifier'), ('standard', 'Standard User')], max_length=20)),
                ('sub_role', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_assign_bouquets', models.BooleanField(default=False)),
                ('can_view_all_data', models.BooleanField(default=False)),
                ('can_manage_payments', models.BooleanField(default=False)),
                ('can_manage_verification', models.BooleanField(default=False)),
                ('can_export_reports', models.BooleanField(default=False)),
                ('can_approve_documents', models.BooleanField(default=False)),
                ('can_send_notifications', models.BooleanField(default=False)),
                ('can_view_pending_verifications', models.BooleanField(default=False)),
                ('can_review_approve', models.BooleanField(default=False)),
                ('can_download_documents', models.BooleanField(default=False)),
                ('can_upload_verification_report', models.BooleanField(default=False)),
                ('can_maintain_audit_log', models.BooleanField(default=False)),
                ('can_notify_users', models.BooleanField(default=False)),
                ('can_add_edit_personal_details', models.BooleanField(default=True)),
                ('can_add_spouse_dependents', models.BooleanField(default=True)),
                ('can_upload_documents', models.BooleanField(default=True)),
                ('can_manage_assets', models.BooleanField(default=True)),
                ('can_manage_liabilities', models.BooleanField(default=True)),
                ('can_manage_businesses', models.BooleanField(default=True)),
                ('can_manage_professional_contacts', models.BooleanField(default=True)),
                ('can_add_beneficiaries', models.BooleanField(default=True)),
                ('can_view_dashboard', models.BooleanField(default=True)),
                ('can_receive_verification_updates', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['role_type', 'name'],
            },
        ),
    ]
