# Generated by Django 5.1.2 on 2025-10-23 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_create_bouquet_and_role_models'),
    ]

    operations = [
        # First, create the new fields as nullable
        migrations.RunSQL(
            "ALTER TABLE accounts_userprofile ADD COLUMN role_id INTEGER NULL;",
            reverse_sql="ALTER TABLE accounts_userprofile DROP COLUMN role_id;"
        ),
        migrations.RunSQL(
            "ALTER TABLE accounts_userprofile ADD COLUMN bouquet_id INTEGER NULL;",
            reverse_sql="ALTER TABLE accounts_userprofile DROP COLUMN bouquet_id;"
        ),
        migrations.RunSQL(
            "ALTER TABLE accounts_userprofile ADD COLUMN subscription_end_date DATE NULL;",
            reverse_sql="ALTER TABLE accounts_userprofile DROP COLUMN subscription_end_date;"
        ),
        migrations.RunSQL(
            "ALTER TABLE accounts_userprofile ADD COLUMN verification_status VARCHAR(20) DEFAULT 'pending';",
            reverse_sql="ALTER TABLE accounts_userprofile DROP COLUMN verification_status;"
        ),
        # Add foreign key constraints
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS accounts_userprofile_role_id_idx ON accounts_userprofile(role_id);",
            reverse_sql="DROP INDEX IF EXISTS accounts_userprofile_role_id_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS accounts_userprofile_bouquet_id_idx ON accounts_userprofile(bouquet_id);",
            reverse_sql="DROP INDEX IF EXISTS accounts_userprofile_bouquet_id_idx;"
        ),
    ]
